version: '2'
services:
  reverse_proxy:
    image: nginx-rp:latest
    volumes:
     - ./nginx-config/basic-rp/:/etc/nginx/default.d/:ro
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    command: /bin/bash -c "nginx -g 'daemon off;'"
